substitutions:
  friendly_name: Guition Display
  dev_topic: esp32-c3-35-inch-display   # used for MQTT topics

packages:
  core: !include core.yaml
  room_page: !include ui/room_page.yaml
  house_page: !include ui/house_page.yaml
